(function(){
  if (window.__AFRO_SUPPLIER_PATCH__) return;
  window.__AFRO_SUPPLIER_PATCH__ = true;
  const API = '/api';
  const TOKEN_KEY = 'pazar_session_token';
  const css = `
    .afro-sup-btn{position:fixed;right:18px;bottom:18px;z-index:2147483000;background:#10b981;color:#fff;border:0;border-radius:999px;padding:13px 18px;font-weight:800;box-shadow:0 8px 28px rgba(0,0,0,.28);cursor:pointer;font-family:Arial,sans-serif}
    .afro-sup-modal,.afro-sup-panel{position:fixed;inset:0;z-index:2147483001;background:rgba(1,20,10,.92);color:#eafff4;font-family:Arial,sans-serif;overflow:auto}
    .afro-sup-card{max-width:920px;margin:45px auto;background:#062216;border:1px solid #135f42;border-radius:18px;padding:22px;box-shadow:0 16px 50px rgba(0,0,0,.35)}
    .afro-sup-row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:12px 0}.afro-sup-row>*{flex:1;min-width:180px}
    .afro-sup-input,.afro-sup-select{background:#03140d;color:#fff;border:1px solid #1b7d59;border-radius:10px;padding:12px;font-weight:700}
    .afro-sup-action{background:#10b981;color:#fff;border:0;border-radius:10px;padding:12px 15px;font-weight:800;cursor:pointer}.afro-sup-danger{background:#ef4444}.afro-sup-ghost{background:#10291e}
    .afro-sup-table{width:100%;border-collapse:collapse;margin-top:16px}.afro-sup-table th,.afro-sup-table td{border-bottom:1px solid #154b36;padding:10px;text-align:left;font-size:14px}.afro-sup-table input{width:90px;background:#03140d;color:#fff;border:1px solid #1b7d59;border-radius:8px;padding:8px}
    .afro-sup-muted{color:#9ccbb8;font-size:13px}.afro-sup-top{display:flex;justify-content:space-between;gap:12px;align-items:center}.afro-sup-msg{margin-top:10px;font-weight:700;color:#fbbf24}
  `;
  function addStyle(){ if(document.getElementById('afro-supplier-style')) return; const s=document.createElement('style'); s.id='afro-supplier-style'; s.textContent=css; document.head.appendChild(s); }
  function getToken(){ const raw=localStorage.getItem(TOKEN_KEY); if(!raw) return ''; try{return JSON.parse(raw)||''}catch(e){return raw.replace(/^"|"$/g,'')} }
  async function api(path,opt={}){ const token=getToken(); const res=await fetch(API+path,{method:opt.method||'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:opt.body?JSON.stringify(opt.body):undefined}); const text=await res.text(); let data=null; try{data=text?JSON.parse(text):null}catch(e){data={detail:text}} if(!res.ok) throw new Error((data&&data.detail)||('Hata: '+res.status)); return data; }
  function el(tag, attrs={}, children=[]){ const n=document.createElement(tag); Object.entries(attrs).forEach(([k,v])=>{ if(k==='class') n.className=v; else if(k==='text') n.textContent=v; else n.setAttribute(k,v); }); (Array.isArray(children)?children:[children]).filter(Boolean).forEach(c=>n.appendChild(typeof c==='string'?document.createTextNode(c):c)); return n; }
  async function currentUser(){ try{return await api('/auth/me')}catch(e){return null} }
  function isSupplierAuthPage(){
    const loc=(location.pathname+' '+location.hash).toLocaleLowerCase('tr-TR');
    return /admin\/(members|member)(\b|\/|$)/.test(loc);
  }
  async function ensureAdminButton(user){
    const old=document.getElementById('afro-supplier-auth-btn');
    if(!user || !['admin','yonetici'].includes(user.role) || !isSupplierAuthPage()){ if(old) old.remove(); return; }
    addStyle();
    if(old) return;
    const b=el('button',{id:'afro-supplier-auth-btn',class:'afro-sup-btn',text:'Tedarikçi Yetkilendir'});
    b.onclick=openAuthModal;
    document.body.appendChild(b);
  }
  async function openAuthModal(){ addStyle(); const old=document.getElementById('afro-supplier-modal'); if(old) old.remove(); const m=el('div',{id:'afro-supplier-modal',class:'afro-sup-modal'}); const card=el('div',{class:'afro-sup-card'}); const title=el('div',{class:'afro-sup-top'},[el('h2',{text:'Tedarikçi Yetkilendir'}),el('button',{class:'afro-sup-action afro-sup-ghost',text:'Kapat'})]); title.querySelector('button').onclick=()=>m.remove(); const msg=el('div',{class:'afro-sup-msg'}); const ident=el('input',{class:'afro-sup-input',placeholder:'Kullanıcı ID veya telefon (örn: 0538...)'}); const sel=el('select',{class:'afro-sup-select'}); sel.appendChild(el('option',{value:'',text:'Yetkiyi kaldır / müşteri yap'})); try{ const sups=await api('/admin/suppliers'); sups.forEach(s=>sel.appendChild(el('option',{value:s.id||s._id,text:s.name||s.id||s._id}))); }catch(e){ msg.textContent='Tedarikçiler alınamadı: '+e.message; } const save=el('button',{class:'afro-sup-action',text:'Kaydet'}); save.onclick=async()=>{ msg.textContent='Kaydediliyor...'; try{ if(!ident.value.trim()) throw new Error('Kullanıcı ID veya telefon gir.'); const r=await api('/admin/users/'+encodeURIComponent(ident.value.trim())+'/supplier',{method:'PUT',body:{supplier_id:sel.value||null}}); msg.textContent=r.supplier_id?'Tedarikçi yetkisi verildi: '+(r.supplier_name||r.supplier_id):'Tedarikçi yetkisi kaldırıldı.'; }catch(e){ msg.textContent='Hata: '+e.message; } }; card.append(title,el('p',{class:'afro-sup-muted',text:'Müşteri telefonunu veya user_id değerini gir, tek bir tedarikçi seç ve kaydet.'}),el('div',{class:'afro-sup-row'},[ident,sel,save]),msg); m.appendChild(card); document.body.appendChild(m); }
  async function renderSupplierPanel(user){ if(!user || user.role!=='supplier') return; addStyle(); if(document.getElementById('afro-supplier-panel')) return; const p=el('div',{id:'afro-supplier-panel',class:'afro-sup-panel'}); const card=el('div',{class:'afro-sup-card'}); const msg=el('div',{class:'afro-sup-msg'}); card.appendChild(el('div',{class:'afro-sup-top'},[el('div',{},[el('h2',{text:'Tedarikçi Paneli'}),el('div',{class:'afro-sup-muted',text:'Sadece sana bağlı ürünleri düzenleyebilirsin.'})]),el('button',{class:'afro-sup-action afro-sup-danger',text:'Çıkış'})])); card.querySelector('.afro-sup-danger').onclick=()=>{localStorage.removeItem(TOKEN_KEY); location.href='/login'}; const holder=el('div',{}); card.append(msg,holder); p.appendChild(card); document.body.appendChild(p); try{ const me=await api('/supplier/me'); card.querySelector('.afro-sup-muted').textContent=(me.name||'Tedarikçi')+' hesabı — sadece kendi ürünlerin listelenir.'; const products=await api('/supplier/products'); if(!products.length){ holder.textContent='Bu tedarikçiye bağlı ürün bulunamadı.'; return; } const table=el('table',{class:'afro-sup-table'}); table.innerHTML='<thead><tr><th>Ürün</th><th>Birim</th><th>Fiyat</th><th>Gel-Al</th><th>Eve Servis</th><th>Stokta</th><th>İşlem</th></tr></thead><tbody></tbody>'; const tb=table.querySelector('tbody'); products.forEach(pr=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${pr.name||''}</td><td>${pr.unit||''}</td><td><input type="number" step="0.01" value="${pr.price??0}"></td><td><input type="number" step="0.01" value="${pr.gel_al_price??pr.price??0}"></td><td><input type="number" step="0.01" value="${pr.eve_servis_price??pr.price??0}"></td><td><select class="afro-sup-select"><option value="true">Var</option><option value="false">Yok</option></select></td><td><button class="afro-sup-action">Kaydet</button></td>`; tr.querySelector('select').value=String(pr.in_stock!==false); tr.querySelector('button').onclick=async()=>{ const ins=tr.querySelectorAll('input'); const st=tr.querySelector('select').value==='true'; msg.textContent='Kaydediliyor...'; try{ await api('/supplier/products/'+encodeURIComponent(pr.id||pr._id),{method:'PUT',body:{price:Number(ins[0].value),gel_al_price:Number(ins[1].value),eve_servis_price:Number(ins[2].value),in_stock:st}}); msg.textContent=(pr.name||'Ürün')+' güncellendi.'; }catch(e){ msg.textContent='Hata: '+e.message; } }; tb.appendChild(tr); }); holder.appendChild(table); }catch(e){ msg.textContent='Tedarikçi paneli açılamadı: '+e.message; } }
  async function tick(){ const u=await currentUser(); await renderSupplierPanel(u); await ensureAdminButton(u); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',tick); else tick();
  setInterval(tick,3000);
})();
